permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Thylong
title: blog
description: "A technical blog of a Core Developer"
keywords: "Python, microservices, go, docker, mongo, postgreSQL"
url: http://thylong.github.io
baseurl: ""
domain_name: thylong.github.io
# google_analytics: UA-52446115-1
repo: http://github.com/thylong/thylong.github.io
disqus_shortname: "thylonggithubio"

author:
  name      : Théotime Leveque
  image     : /assets/images/author.jpg
  email     : theotime.leveque@gmail.com
  url       : http://github.com/thylong
  facebook  : http://facebook.com/theotime.leveque
  twitter   : http://twitter.com/thylnheo
  instagram : http://instagram.com/theotime.leveque
  github    : http://github.com/thylong
  linkedin  : https://www.linkedin.com/pub/th%C3%A9otime-l%C3%A9v%C3%A8que/46/66/496
  bio       : "Core Developer, Python fan and art enthousiast"

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
